import { useState } from "react";
import { QuestionCard } from "@/components/QuestionCard";
import type { BankQuestion } from "@/game/types";

export type DiagramFixtureVariant = "svg" | "source" | "sourceGraph" | "thermoregulation" | "lizardGraph" | "osmosis" | "fermentation" | "variation" | "ovary" | "embryo" | "beak" | "vertebra" | "digestive0413" | "euglena0749" | "beak1225" | "kclo3Oxygen" | "idealGas" | "photosynthesis0562" | "broken" | "wide" | "portrait" | "none";

const questions: Record<DiagramFixtureVariant, BankQuestion> = {
  svg: {
    id: "fixture-diagram-svg-potometer",
    subject: "Biology",
    topic: "Plant Biology",
    subtopic: "Transpiration",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "svg", "potometer"],
    source: "Fixture — verified learner SVG",
    question: "Which apparatus in the diagram is used to measure the rate of transpiration in a leafy shoot?",
    options: ["Hygrometer", "Photometer", "Potometer", "Anemometer"],
    answer_index: 2,
    answer_text: "Potometer",
    explanation: "A potometer estimates water uptake by a leafy shoot and is used to investigate transpiration.",
    diagram_url: "/manus-storage/jamb-quest-potometer_0ff84706.svg",
  },
  source: {
    id: "fixture-diagram-source-liquid-force",
    subject: "Physics",
    topic: "Motion",
    subtopic: "Forces in fluids",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only crop", "forces"],
    source: "Fixture — verified owner original crop",
    question: "The acceleration of the body shown in the liquid is",
    options: ["10.0 m/s²", "20.0 m/s²", "7.5 m/s²", "6.8 m/s²"],
    answer_index: 2,
    answer_text: "7.5 m/s²",
    explanation: "The diagram supplies the force information needed to calculate the resultant force and acceleration.",
    diagram_url: "/manus-storage/owner-phy-diagram-2026-008-source-panel_acaa185f.png",
  },
  sourceGraph: {
    id: "fixture-diagram-source-cockroach-graph",
    subject: "Biology",
    topic: "Natural habitats",
    subtopic: "Environmental factors",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only crop", "graph"],
    source: "Fixture — verified owner-source graph",
    question: "From the diagram above the optimal temperature for breeding cockroaches is",
    options: ["15 °C", "19 °C", "24 °C", "33 °C"],
    answer_index: 2,
    answer_text: "24 °C",
    explanation: "The 24 °C curve reaches the highest number of cockroaches in the graph.",
    diagram_url: "/manus-storage/biology-0396-schoolngr-source-panel_658f04ef.png",
  },
  thermoregulation: {
    id: "fixture-diagram-thermoregulation-graph",
    subject: "Biology",
    topic: "Support and movement",
    subtopic: "Temperature regulation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "thermoregulation graph"],
    source: "Fixture — verified JAMB 2008 original graph",
    question: "Use the diagram above to answer this question. The animal represented by I is a",
    options: ["poikilotherm", "homoiotherm", "carnivore", "herbivore"],
    answer_index: 1,
    answer_text: "homoiotherm",
    explanation: "Line I remains nearly constant as external temperature changes, which identifies a homoiotherm.",
    diagram_url: "/manus-storage/biology-0518-myschool-original_32575fb8.png",
  },
  lizardGraph: {
    id: "fixture-diagram-lizard-thermoregulation-graph",
    subject: "Biology",
    topic: "Coordination and control",
    subtopic: "Thermoregulation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "lizard temperature graph"],
    source: "Fixture — verified JAMB 2018 original graph",
    question: "The graph above shows the results of a laboratory investigation which measured the body temperatures of a lizard and a bird under changing artificial conditions. Use it to answer the question. What physiological term can be used to describe the regulation of the body temperature of the lizard?",
    options: ["Homeostasis", "Homoiothermy", "Poikilothermy", "Osmoregulation"],
    answer_index: 2,
    answer_text: "Poikilothermy",
    explanation: "The lizard's body temperature changes with environmental temperature, so it is poikilothermic.",
    diagram_url: "/manus-storage/biology-0870-myschool-original_c780fc2d.jpeg",
  },
  osmosis: {
    id: "fixture-diagram-thistle-funnel-osmosis",
    subject: "Biology",
    topic: "Transport",
    subtopic: "Osmosis",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "thistle funnel osmosis"],
    source: "Fixture — verified JAMB 2018 original apparatus",
    question: "Use the diagram shown to answer the question. The experiment above is used to demonstrate the process of",
    options: ["transportation", "water culture", "diffusion", "osmosis"],
    answer_index: 3,
    answer_text: "osmosis",
    explanation: "The thistle-funnel apparatus demonstrates water movement through a selectively permeable membrane by osmosis.",
    diagram_url: "/manus-storage/biology-0905-schoolngr-original_705e2a37.png",
  },
  fermentation: {
    id: "fixture-diagram-fermentation-apparatus",
    subject: "Biology",
    topic: "Respiration",
    subtopic: "Anaerobic respiration",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "fermentation apparatus"],
    source: "Fixture — verified JAMB 2011 original apparatus",
    question: "Use the diagram above to answer this question. The gas evolved in the process is",
    options: ["carbon (IV) oxide", "nitrogen", "oxygen", "carbon (II) oxide"],
    answer_index: 0,
    answer_text: "carbon (IV) oxide",
    explanation: "Yeast breaks down the sucrose anaerobically, producing carbon(IV) oxide that passes into the lime water.",
    diagram_url: "/manus-storage/biology-0600-schoolngr-original_413d60ab.png",
  },
  variation: {
    id: "fixture-diagram-continuous-variation-graph",
    subject: "Biology",
    topic: "Population ecology",
    subtopic: "Variation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "continuous variation graph"],
    source: "Fixture — verified JAMB 2012 original graph",
    question: "Use the diagram above to answer this question. The graph illustrates",
    options: ["the highest frequency for height of 2 metres", "a discontinuously varying character", "a continuously varying character", "total yield in a cassava farm"],
    answer_index: 2,
    answer_text: "a continuously varying character",
    explanation: "The smooth distribution across a range of heights is characteristic of continuous variation.",
    diagram_url: "/manus-storage/biology-0645-myschool-original_3340a9ed.jpg",
  },
  ovary: {
    id: "fixture-diagram-ovary-function",
    subject: "Biology",
    topic: "Reproduction",
    subtopic: "Female reproductive system",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "ovary function"],
    source: "Fixture — verified JAMB 2012 original reproductive system",
    question: "Use the diagram above to answer this question. The function of the part labelled III is to",
    options: ["produce egg cells", "protect sperms during fertilization", "secrete hormones during coitus", "protect the developing embryo"],
    answer_index: 0,
    answer_text: "produce egg cells",
    explanation: "Label III is the ovary, which produces egg cells.",
    diagram_url: "/manus-storage/biology-0649-myschool-original_0ce93479.jpg",
  },
  embryo: {
    id: "fixture-diagram-embryo-location",
    subject: "Biology",
    topic: "Reproduction",
    subtopic: "Female reproductive system",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "byte-identical original", "embryo location"],
    source: "Fixture — verified paired JAMB 2012 original reproductive system",
    question: "Use the diagram above to answer this question. The developing embryo is usually contained in the part labelled",
    options: ["IV", "III", "II", "I"],
    answer_index: 2,
    answer_text: "II",
    explanation: "Label II is the uterus, where the developing embryo is contained.",
    diagram_url: "/manus-storage/biology-0649-myschool-original_0ce93479.jpg",
  },
  beak: {
    id: "fixture-diagram-source-beak",
    subject: "Biology",
    topic: "Adaptations of organisms",
    subtopic: "Structural adaptation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only original", "beak"],
    source: "Fixture — verified JAMB 2022 original",
    question: "The beak structure of the organism is best adapted for?",
    options: ["pecking grass", "killing and picking fish", "pecking woods", "sucking nectars"],
    answer_index: 3,
    answer_text: "sucking nectars",
    explanation: "The long, slender pointed beak is adapted for reaching into flowers to take nectar.",
    diagram_url: "/manus-storage/biology-1102-myschool-source-panel_41a60dd5.png",
  },
  vertebra: {
    id: "fixture-diagram-source-vertebra",
    subject: "Biology",
    topic: "Support and movement",
    subtopic: "Vertebral column",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "alternate original", "vertebra"],
    source: "Fixture — verified JAMB 2020 alternate original",
    question: "Use the diagram to answer the question. The vertebra illustrated is",
    options: ["Lumbar", "Thoracic", "Caudal", "Cervical"],
    answer_index: 1,
    answer_text: "Thoracic",
    explanation: "The illustrated vertebra is thoracic. Its long neural spine and rib-articulating processes identify it as a thoracic vertebra.",
    diagram_url: "/manus-storage/biology-1020-quizzerweb-original_595264ba.webp",
  },
  digestive0413: {
    id: "fixture-diagram-jamb-2005-digestive-system",
    subject: "Biology",
    topic: "Plant and mammal structure",
    subtopic: "Human digestive system",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "digestive system", "JAMB 2005"],
    source: "Fixture — verified JAMB 2005 original",
    question: "From the diagram above the part labelled IV represents the",
    options: ["colon", "ileum", "caecum", "duodenum"],
    answer_index: 3,
    answer_text: "duodenum",
    explanation: "Label IV points to the first section of the small intestine immediately after the stomach: the duodenum.",
    diagram_url: "/manus-storage/biology-0413-schoolngr-source-only-v2_75d0867c.png",
  },
  euglena0749: {
    id: "fixture-diagram-jamb-2014-euglena",
    subject: "Biology",
    topic: "Nutrition and digestion",
    subtopic: "Photosynthesis",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "Euglena", "JAMB 2014"],
    source: "Fixture — verified JAMB 2014 original",
    question: "Use the diagram above to answer this question. The part responsible for photosynthesis is labelled",
    options: ["III", "IV", "I", "II"],
    answer_index: 0,
    answer_text: "III",
    explanation: "In the exact source figure, label III identifies the chloroplast-containing part of Euglena. Chloroplasts contain chlorophyll and carry out photosynthesis.",
    diagram_url: "/manus-storage/biology-0749-schoolngr-original_64d08afe.png",
  },
  beak1225: {
    id: "fixture-diagram-jamb-2025-beak",
    subject: "Biology",
    topic: "Adaptations of organisms",
    subtopic: "Bird beak adaptations",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "bird beak", "JAMB 2025"],
    source: "Fixture — verified JAMB 2025 original",
    question: "Use the diagram above to answer the question that follows. The structure labelled I is adapted for",
    options: ["tearing", "sieving", "boring", "sucking"],
    answer_index: 3,
    answer_text: "sucking",
    explanation: "In the exact source figure, label I points to the long, narrow upper beak adapted for reaching into tubular flowers to suck nectar.",
    diagram_url: "/manus-storage/biology-1225-myschool-original_353283bf.png",
  },
  kclo3Oxygen: {
    id: "fixture-diagram-jamb-2009-kclo3-oxygen-graph",
    subject: "Chemistry",
    topic: "Rates of reaction",
    subtopic: "Reaction progress curves",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "oxygen evolution", "JAMB 2009"],
    source: "Fixture — verified JAMB 2009 original",
    question: "In the diagram above, which of the curves represents the evolution of oxygen with time in the equation 2KClO3(s) → 2KCl(s) + 3O2(g)?",
    options: ["X", "Y", "Z", "R"],
    answer_index: 3,
    answer_text: "R",
    explanation: "Curve R begins at the origin, rises as oxygen is evolved, and levels off as potassium chlorate is used up.",
    diagram_url: "/manus-storage/chemistry-kclo3-schoolngr-original_4374f259.png",
  },
  idealGas: {
    id: "fixture-diagram-jamb-2011-ideal-gas-graph",
    subject: "Chemistry",
    topic: "Kinetic theory of matter and gases",
    subtopic: "Ideal and real gases",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "ideal gas", "JAMB 2011"],
    source: "Fixture — verified JAMB 2011 original",
    question: "From the diagram above, an ideal gas can be represented by:",
    options: ["M.", "N.", "K.", "L."],
    answer_index: 1,
    answer_text: "N.",
    explanation: "In the exact source graph, N is the horizontal line, so its PV value remains unchanged as pressure varies. It represents ideal gas behaviour.",
    diagram_url: "/manus-storage/chemistry-ideal-gas-schoolngr-original_002271ae.png",
  },
  photosynthesis0562: {
    id: "fixture-diagram-jamb-2010-photosynthesis-arrow",
    subject: "Biology",
    topic: "Nutrition and digestion",
    subtopic: "Photosynthesis",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "photosynthesis arrows", "JAMB 2010"],
    source: "Fixture — verified JAMB 2010 original",
    question: "Use the diagram above to answer this question. During photosynthesis, the arrow labeled II represents the?",
    options: ["escape of mineral salts", "absorption of energy from the sun", "release of carbon (IV) oxide", "release of oxygen as a by-product"],
    answer_index: 3,
    answer_text: "release of oxygen as a by-product",
    explanation: "In the exact source figure, arrow II shows oxygen leaving the leaf during photosynthesis. Oxygen is released as a by-product of the process.",
    diagram_url: "/manus-storage/biology-0562-testdriller-original_301dd58c.png",
  },
  broken: {
    id: "fixture-diagram-unavailable",
    subject: "Biology",
    topic: "Adaptations of organisms",
    subtopic: "Structural adaptation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "failed image", "fallback"],
    source: "Fixture — intentional failed diagram URL",
    question: "This question must never leave an empty answer-critical diagram frame.",
    options: ["Option A", "Option B", "Option C", "Option D"],
    answer_index: 0,
    answer_text: "Option A",
    explanation: "The error state must be explicit instead of showing a blank diagram area.",
    diagram_url: "/manus-storage/intentional-missing-diagram-fixture.png",
  },
  wide: {
    id: "fixture-diagram-wide-energy-profile",
    subject: "Chemistry",
    topic: "Energy changes",
    subtopic: "Energy profiles",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "wide", "energy profile"],
    source: "Fixture — verified owner original",
    question: "In the energy profile diagram above, X represents the:",
    options: ["enthalpy.", "enthalpy change.", "activation energy.", "activated complex."],
    answer_index: 2,
    answer_text: "activation energy.",
    explanation: "The point marked X is at the top of the energy barrier.",
    diagram_url: "/manus-storage/chemistry-energy-profile-original_3e1f7670.png",
  },
  portrait: {
    id: "fixture-diagram-portrait-digestive-system",
    subject: "Biology",
    topic: "Nutrition — Human digestive system",
    subtopic: "Digestive system",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "portrait", "biology"],
    source: "Fixture — verified owner original",
    question: "The part labelled II is the",
    options: ["liver", "pancreas", "lung", "stomach"],
    answer_index: 3,
    answer_text: "stomach",
    explanation: "Label II identifies the J-shaped organ between the oesophagus and small intestine.",
    diagram_url: "/manus-storage/jamb-quest-biology-digestive-system_e222260a.png",
  },
  none: {
    id: "fixture-diagram-none-fallback",
    subject: "Chemistry",
    topic: "Chemical equilibria",
    subtopic: "Equilibrium constants",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "no diagram", "fallback"],
    source: "Fixture — intentional no-diagram fallback",
    question: "For the equilibrium 2XY₃(g) ⇌ X₂(g) + 3Y₂(g), the expression for Kc is",
    options: ["[2XY₃] / [X₂][3Y₂]", "[X₂][3Y₂] / 2XY₃", "[XY₃]² / [X₂][Y₂]", "[X₂][Y₂]³ / [XY₃]²"],
    answer_index: 3,
    answer_text: "[X₂][Y₂]³ / [XY₃]²",
    explanation: "The question is fully answerable from its equation and options, so no diagram is rendered.",
  },
};

const labels: Record<DiagramFixtureVariant, string> = {
  svg: "Browser-delivered SVG",
  source: "Original-only source crop",
  sourceGraph: "Original-only source graph",
  thermoregulation: "Repaired original thermoregulation graph",
  lizardGraph: "Repaired original lizard-and-bird graph",
  osmosis: "Repaired original thistle-funnel apparatus",
  fermentation: "Repaired original fermentation apparatus",
  variation: "Repaired original continuous-variation graph",
  ovary: "Repaired original ovary-function diagram",
  embryo: "Repaired paired embryo-location diagram",
  beak: "Repaired original beak figure",
  vertebra: "Repaired alternate-source vertebra figure",
  digestive0413: "Repaired exact JAMB 2005 digestive-system figure",
  euglena0749: "Repaired exact JAMB 2014 Euglena figure",
  beak1225: "Repaired exact JAMB 2025 bird-beak figure",
  kclo3Oxygen: "Repaired exact JAMB 2009 oxygen-evolution graph",
  idealGas: "Repaired exact JAMB 2011 ideal-gas graph",
  photosynthesis0562: "Repaired exact JAMB 2010 photosynthesis-arrow figure",
  broken: "Intentional unavailable-diagram fallback",
  wide: "Wide energy profile",
  portrait: "Portrait Biology diagram",
  none: "Held/no-diagram fallback",
};

export function DiagramRenderingFixture({ variant }: { variant: DiagramFixtureVariant }) {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const question = questions[variant];
  return (
    <main className="p-4 md:p-8">
      <div className="mx-auto mb-4 max-w-[760px] rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950">
        <strong>Diagram rendering fixture:</strong> {labels[variant]}
      </div>
      <QuestionCard question={question} index={0} total={1} selectedIndex={selectedIndex} answered={false} onSelect={setSelectedIndex} onSubmit={() => undefined} onNext={() => undefined} />
    </main>
  );
}
