import { useState } from "react";
import { QuestionCard } from "@/components/QuestionCard";
import type { BankQuestion } from "@/game/types";

export type DiagramFixtureVariant = "svg" | "source" | "sourceGraph" | "thermoregulation" | "fermentation" | "beak" | "vertebra" | "broken" | "wide" | "portrait" | "none";

const questions: Record<DiagramFixtureVariant, BankQuestion> = {
  svg: {
    id: "fixture-diagram-svg-potometer",
    subject: "Biology",
    topic: "Plant Biology",
    subtopic: "Transpiration",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "svg", "potometer"],
    source: "Fixture — verified learner SVG",
    question: "Which apparatus in the diagram is used to measure the rate of transpiration in a leafy shoot?",
    options: ["Hygrometer", "Photometer", "Potometer", "Anemometer"],
    answer_index: 2,
    answer_text: "Potometer",
    explanation: "A potometer estimates water uptake by a leafy shoot and is used to investigate transpiration.",
    diagram_url: "/manus-storage/jamb-quest-potometer_0ff84706.svg",
  },
  source: {
    id: "fixture-diagram-source-liquid-force",
    subject: "Physics",
    topic: "Motion",
    subtopic: "Forces in fluids",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only crop", "forces"],
    source: "Fixture — verified owner original crop",
    question: "The acceleration of the body shown in the liquid is",
    options: ["10.0 m/s²", "20.0 m/s²", "7.5 m/s²", "6.8 m/s²"],
    answer_index: 2,
    answer_text: "7.5 m/s²",
    explanation: "The diagram supplies the force information needed to calculate the resultant force and acceleration.",
    diagram_url: "/manus-storage/owner-phy-diagram-2026-008-source-panel_acaa185f.png",
  },
  sourceGraph: {
    id: "fixture-diagram-source-cockroach-graph",
    subject: "Biology",
    topic: "Natural habitats",
    subtopic: "Environmental factors",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only crop", "graph"],
    source: "Fixture — verified owner-source graph",
    question: "From the diagram above the optimal temperature for breeding cockroaches is",
    options: ["15 °C", "19 °C", "24 °C", "33 °C"],
    answer_index: 2,
    answer_text: "24 °C",
    explanation: "The 24 °C curve reaches the highest number of cockroaches in the graph.",
    diagram_url: "/manus-storage/biology-0396-schoolngr-source-panel_658f04ef.png",
  },
  thermoregulation: {
    id: "fixture-diagram-thermoregulation-graph",
    subject: "Biology",
    topic: "Support and movement",
    subtopic: "Temperature regulation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "thermoregulation graph"],
    source: "Fixture — verified JAMB 2008 original graph",
    question: "Use the diagram above to answer this question. The animal represented by I is a",
    options: ["poikilotherm", "homoiotherm", "carnivore", "herbivore"],
    answer_index: 1,
    answer_text: "homoiotherm",
    explanation: "Line I remains nearly constant as external temperature changes, which identifies a homoiotherm.",
    diagram_url: "/manus-storage/biology-0518-myschool-original_32575fb8.png",
  },
  fermentation: {
    id: "fixture-diagram-fermentation-apparatus",
    subject: "Biology",
    topic: "Respiration",
    subtopic: "Anaerobic respiration",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "exact original", "fermentation apparatus"],
    source: "Fixture — verified JAMB 2011 original apparatus",
    question: "Use the diagram above to answer this question. The gas evolved in the process is",
    options: ["carbon (IV) oxide", "nitrogen", "oxygen", "carbon (II) oxide"],
    answer_index: 0,
    answer_text: "carbon (IV) oxide",
    explanation: "Yeast breaks down the sucrose anaerobically, producing carbon(IV) oxide that passes into the lime water.",
    diagram_url: "/manus-storage/biology-0600-schoolngr-original_413d60ab.png",
  },
  beak: {
    id: "fixture-diagram-source-beak",
    subject: "Biology",
    topic: "Adaptations of organisms",
    subtopic: "Structural adaptation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "source-only original", "beak"],
    source: "Fixture — verified JAMB 2022 original",
    question: "The beak structure of the organism is best adapted for?",
    options: ["pecking grass", "killing and picking fish", "pecking woods", "sucking nectars"],
    answer_index: 3,
    answer_text: "sucking nectars",
    explanation: "The long, slender pointed beak is adapted for reaching into flowers to take nectar.",
    diagram_url: "/manus-storage/biology-1102-myschool-source-panel_41a60dd5.png",
  },
  vertebra: {
    id: "fixture-diagram-source-vertebra",
    subject: "Biology",
    topic: "Support and movement",
    subtopic: "Vertebral column",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "alternate original", "vertebra"],
    source: "Fixture — verified JAMB 2020 alternate original",
    question: "Use the diagram to answer the question. The vertebra illustrated is",
    options: ["Lumbar", "Thoracic", "Caudal", "Cervical"],
    answer_index: 1,
    answer_text: "Thoracic",
    explanation: "The illustrated vertebra is thoracic. Its long neural spine and rib-articulating processes identify it as a thoracic vertebra.",
    diagram_url: "/manus-storage/biology-1020-quizzerweb-original_595264ba.webp",
  },
  broken: {
    id: "fixture-diagram-unavailable",
    subject: "Biology",
    topic: "Adaptations of organisms",
    subtopic: "Structural adaptation",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "failed image", "fallback"],
    source: "Fixture — intentional failed diagram URL",
    question: "This question must never leave an empty answer-critical diagram frame.",
    options: ["Option A", "Option B", "Option C", "Option D"],
    answer_index: 0,
    answer_text: "Option A",
    explanation: "The error state must be explicit instead of showing a blank diagram area.",
    diagram_url: "/manus-storage/intentional-missing-diagram-fixture.png",
  },
  wide: {
    id: "fixture-diagram-wide-energy-profile",
    subject: "Chemistry",
    topic: "Energy changes",
    subtopic: "Energy profiles",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "wide", "energy profile"],
    source: "Fixture — verified owner original",
    question: "In the energy profile diagram above, X represents the:",
    options: ["enthalpy.", "enthalpy change.", "activation energy.", "activated complex."],
    answer_index: 2,
    answer_text: "activation energy.",
    explanation: "The point marked X is at the top of the energy barrier.",
    diagram_url: "/manus-storage/chemistry-energy-profile-original_3e1f7670.png",
  },
  portrait: {
    id: "fixture-diagram-portrait-digestive-system",
    subject: "Biology",
    topic: "Nutrition — Human digestive system",
    subtopic: "Digestive system",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "portrait", "biology"],
    source: "Fixture — verified owner original",
    question: "The part labelled II is the",
    options: ["liver", "pancreas", "lung", "stomach"],
    answer_index: 3,
    answer_text: "stomach",
    explanation: "Label II identifies the J-shaped organ between the oesophagus and small intestine.",
    diagram_url: "/manus-storage/jamb-quest-biology-digestive-system_e222260a.png",
  },
  none: {
    id: "fixture-diagram-none-fallback",
    subject: "Chemistry",
    topic: "Chemical equilibria",
    subtopic: "Equilibrium constants",
    difficulty: "medium",
    question_type: "multiple_choice",
    tags: ["fixture", "no diagram", "fallback"],
    source: "Fixture — intentional no-diagram fallback",
    question: "For the equilibrium 2XY₃(g) ⇌ X₂(g) + 3Y₂(g), the expression for Kc is",
    options: ["[2XY₃] / [X₂][3Y₂]", "[X₂][3Y₂] / 2XY₃", "[XY₃]² / [X₂][Y₂]", "[X₂][Y₂]³ / [XY₃]²"],
    answer_index: 3,
    answer_text: "[X₂][Y₂]³ / [XY₃]²",
    explanation: "The question is fully answerable from its equation and options, so no diagram is rendered.",
  },
};

const labels: Record<DiagramFixtureVariant, string> = {
  svg: "Browser-delivered SVG",
  source: "Original-only source crop",
  sourceGraph: "Original-only source graph",
  thermoregulation: "Repaired original thermoregulation graph",
  fermentation: "Repaired original fermentation apparatus",
  beak: "Repaired original beak figure",
  vertebra: "Repaired alternate-source vertebra figure",
  broken: "Intentional unavailable-diagram fallback",
  wide: "Wide energy profile",
  portrait: "Portrait Biology diagram",
  none: "Held/no-diagram fallback",
};

export function DiagramRenderingFixture({ variant }: { variant: DiagramFixtureVariant }) {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const question = questions[variant];
  return (
    <main className="p-4 md:p-8">
      <div className="mx-auto mb-4 max-w-[760px] rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950">
        <strong>Diagram rendering fixture:</strong> {labels[variant]}
      </div>
      <QuestionCard question={question} index={0} total={1} selectedIndex={selectedIndex} answered={false} onSelect={setSelectedIndex} onSubmit={() => undefined} onNext={() => undefined} />
    </main>
  );
}
