export type SyllabusDetailSubject = "Use of English" | "Biology" | "Chemistry" | "Physics";
export type SyllabusTopicDetail = { objective: string; subtopics: readonly string[]; source: "supplied-pdf" };

const detail = (objective: string, ...subtopics: string[]): SyllabusTopicDetail => ({ objective, subtopics, source: "supplied-pdf" });

export const SYLLABUS_JOURNEY_DETAILS: Record<SyllabusDetailSubject, Record<string, SyllabusTopicDetail>> = {
  "Use of English": {
    "Comprehension passages": detail("Read closely, identify stated and implied meaning, and use context to answer accurately.", "Main ideas and supporting details", "Inference and attitude", "Vocabulary in context", "Passage structure"),
    Summary: detail("Identify key ideas and express them in clear, economical sentences without changing meaning.", "Topic sentences", "Essential points", "Paraphrase", "Concise expression"),
    "Cloze passages": detail("Use grammar, vocabulary, meaning, and register together to complete a passage accurately.", "Context clues", "Grammar fit", "Collocation", "Register"),
    "Reading text": detail("Read the prescribed text for plot, character, setting, theme, and language choices.", "Plot and events", "Characters", "Themes", "Setting and style"),
    "Sentence meaning": detail("Interpret sentences accurately, including relationships, emphasis, and implied meaning.", "Sentence interpretation", "Logical relationships", "Tone and implication", "Paraphrase"),
    Synonyms: detail("Choose words nearest in meaning while preserving the context of the sentence.", "Contextual meaning", "Word choice", "Near meaning", "Register"),
    Antonyms: detail("Choose the word opposite in meaning within the context of the sentence.", "Opposite meaning", "Contextual contrast", "Prefix and word form", "Register"),
    "Clause and sentence patterns": detail("Recognise clause functions and build or interpret correct sentence structures.", "Independent and dependent clauses", "Sentence patterns", "Direct and reported speech", "Active and passive voice"),
    "Word classes": detail("Identify how words function in sentences and use the appropriate form.", "Nouns and pronouns", "Verbs and adjectives", "Adverbs and prepositions", "Determiners and conjunctions"),
    "Tense, aspect, number and agreement": detail("Use correct verb forms and grammatical agreement in standard English.", "Verb tenses", "Aspect", "Singular and plural", "Subject–verb agreement", "Question tags"),
    Mechanics: detail("Apply standard punctuation, spelling, capitalization, and paragraph conventions.", "Punctuation", "Spelling", "Capital letters", "Paragraphing"),
    "Ordinary, figurative and idiomatic usage": detail("Distinguish literal, figurative, and idiomatic Standard British English usage.", "Ordinary usage", "Figurative expressions", "Idioms", "Collocations", "Formal register"),
    Vowels: detail("Distinguish vowel sounds in words and connected speech.", "Monophthongs", "Diphthongs", "Triphthongs", "Sound–spelling differences"),
    Consonants: detail("Identify consonant sounds and clusters in standard pronunciation.", "Consonant types", "Consonant clusters", "Articulation", "Minimal pairs"),
    "Rhymes and homophones": detail("Recognise sound relationships between words and distinguish same-sounding forms.", "End rhyme", "Homophones", "Sound patterns", "Word recognition"),
    "Word stress": detail("Identify the syllable carrying primary stress in mono- and polysyllabic words.", "Syllables", "Primary stress", "Noun–verb stress shifts", "Pronunciation"),
    "Emphatic stress": detail("Interpret how stress changes emphasis and meaning in connected speech.", "Focus words", "Contrastive stress", "Intonation context", "Spoken meaning"),
    "Approved reading text": detail("Read the approved text closely and support answers with accurate events, characters, and themes.", "Chapters and events", "Characters", "Themes", "Setting", "Language and conflict"),
  },
  Biology: {
    "Living organisms and organization": detail("Distinguish living things and relate cell parts to organisation and function.", "Characteristics of living things", "Plant and animal cells", "Cell components", "Levels of organisation"),
    "Evolution and classification": detail("Classify organisms and trace increasing complexity across major groups.", "Monera and Protista", "Fungi", "Plant groups", "Invertebrates", "Vertebrates"),
    "Adaptations of organisms": detail("Explain structural, functional, and behavioural adaptations to habitat and way of life.", "Adaptive colouration", "Social behaviour", "Feeding adaptations", "Defence", "Water and temperature conservation"),
    "Plant and mammal structure": detail("Relate internal structures of flowering plants and mammals to their functions.", "Root, stem and leaf", "Supporting tissues", "Mammalian organs", "Digestive, reproductive and excretory systems"),
    "Nutrition and digestion": detail("Compare nutrition modes and explain plant and animal nutrition, food tests, and digestion.", "Autotrophic and heterotrophic nutrition", "Photosynthesis and chemosynthesis", "Food classes and tests", "Teeth and alimentary canal", "Digestive enzymes"),
    Transport: detail("Explain why materials move in organisms and compare plant and animal transport systems.", "Blood and lymph", "Heart and vessels", "Xylem and phloem", "Diffusion and osmosis", "Transpiration and active transport"),
    Respiration: detail("Explain aerobic and anaerobic respiration and relate respiratory surfaces to gas exchange.", "Respiratory organs", "Aerobic respiration", "Anaerobic respiration", "Gas exchange", "Energy release"),
    Excretion: detail("Identify excretory products and relate excretory organs to osmoregulation.", "Excretory products", "Kidney structure", "Urine formation", "Osmoregulation", "Plant excretion"),
    "Support and movement": detail("Relate support tissues, skeletons, joints, and muscles to movement.", "Plant support", "Mammalian skeleton", "Joints", "Muscles", "Locomotion"),
    Reproduction: detail("Explain sexual and asexual reproduction, fertilisation, and development in plants and animals.", "Asexual reproduction", "Flower structure", "Pollination and fertilisation", "Human reproduction", "Development"),
    Growth: detail("Describe growth, its measurement, and factors that influence development.", "Growth patterns", "Seed germination", "Hormonal control", "Measurement of growth", "Development"),
    "Coordination and control": detail("Explain nervous and hormonal coordination, sense organs, and behaviour.", "Nervous system", "Endocrine glands", "Sense organs", "Reflex action", "Tropisms and behaviour"),
    "Factors affecting distribution": detail("Relate physical and biological factors to where organisms live.", "Temperature", "Water and humidity", "Light", "Soil factors", "Biotic factors"),
    "Symbiotic interactions": detail("Distinguish interactions between organisms and explain their effects.", "Mutualism", "Commensalism", "Parasitism", "Predation", "Competition"),
    "Natural habitats": detail("Describe habitat features and adaptations of organisms in them.", "Aquatic habitats", "Terrestrial habitats", "Arboreal habitats", "Adaptation to habitat"),
    "Nigerian biomes": detail("Identify Nigerian vegetation zones and relate climate to their organisms.", "Rainforest", "Guinea savanna", "Sudan savanna", "Sahel savanna", "Mangrove and freshwater swamp"),
    "Population ecology": detail("Use population concepts to explain changes in organism numbers.", "Population size", "Density", "Growth curves", "Natality and mortality", "Carrying capacity"),
    Soil: detail("Describe soil composition, properties, and importance to living things.", "Soil profile", "Soil texture", "Water retention", "Soil organisms", "Soil conservation"),
    "Humans and environment": detail("Explain human impacts on ecosystems and practical conservation responses.", "Pollution", "Deforestation", "Conservation", "Natural resources", "Public and community health"),
    Variation: detail("Distinguish continuous and discontinuous variation and apply it to real examples.", "Continuous variation", "Discontinuous variation", "Environmental influence", "Frequency distributions", "Fingerprints and blood groups"),
    Heredity: detail("Explain inheritance, chromosomes, simple genetic probability, and applications.", "Heritable characters", "DNA and chromosomes", "Meiosis and fertilisation", "Crosses and probability", "Sex-linked traits"),
    Biotechnology: detail("Identify biotechnology applications and evaluate their uses in daily life.", "Agriculture", "Medicine", "Pharmaceuticals", "Food industry", "Biosafety"),
    "Theories of evolution": detail("Explain organic evolution and compare major evolutionary ideas.", "Lamarck", "Darwin", "Organic evolution", "Adaptation over time"),
    "Evidence of evolution": detail("Use scientific evidence to support evolutionary explanations.", "Fossils", "Comparative anatomy", "Embryology", "Genetic evidence", "Mutation"),
  },
  Chemistry: {
    "Separation of mixtures": detail("Choose and explain suitable methods for separating and purifying mixtures.", "Filtration", "Evaporation and crystallisation", "Distillation", "Sublimation", "Chromatography"),
    "Chemical combination": detail("Use chemical laws and mole relationships to solve composition and formula problems.", "Laws of chemical combination", "Relative atomic mass", "Mole concept", "Empirical formula", "Stoichiometry"),
    "Kinetic theory of matter and gases": detail("Explain particle behaviour in solids, liquids, gases, and gas-law situations.", "Particle theory", "Gas pressure", "Gas laws", "Diffusion", "Molar volume"),
    "Atomic structure and bonding": detail("Relate atomic structure and bonding to chemical properties.", "Atoms and isotopes", "Electronic configuration", "Ionic bonding", "Covalent bonding", "Metallic bonding"),
    "Nuclear chemistry": detail("Explain radioactivity, nuclear changes, and practical uses and risks.", "Radioactivity", "Alpha, beta and gamma", "Half-life", "Nuclear equations", "Applications and safety"),
    Solubility: detail("Use solubility ideas and curves to predict dissolution and crystallisation.", "Solubility curves", "Saturated solutions", "Solubility rules", "Crystallisation", "Water of crystallisation"),
    "Environmental pollution": detail("Identify sources, effects, and control of pollution in air, water, and soil.", "Air pollution", "Water pollution", "Soil pollution", "Greenhouse effect", "Control measures"),
    "Acids, bases and salts": detail("Classify acids and bases, use pH, and explain salt preparation and properties.", "Acids and alkalis", "Indicators and pH", "Neutralisation", "Salt preparation", "Hydrolysis"),
    "Oxidation and reduction": detail("Recognise redox changes and use oxidation numbers in chemical reasoning.", "Oxidation number", "Oxidising agents", "Reducing agents", "Redox equations", "Corrosion"),
    Electrolysis: detail("Predict products of electrolysis and explain industrial applications.", "Electrolytes", "Electrodes", "Electrolysis of solutions", "Faraday ideas", "Electroplating"),
    "Energy changes": detail("Describe energy changes in reactions and interpret energy diagrams.", "Exothermic reactions", "Endothermic reactions", "Enthalpy change", "Activation energy", "Energy profiles"),
    "Rates of reaction": detail("Explain and predict factors that affect reaction rate.", "Collision theory", "Concentration", "Temperature", "Surface area", "Catalysts"),
    "Chemical equilibria": detail("Use reversible-reaction ideas to explain dynamic equilibrium and shifts.", "Reversible reactions", "Dynamic equilibrium", "Le Chatelier principle", "Equilibrium constant", "Industrial equilibrium"),
    "Non-metals and their compounds": detail("Describe key non-metals and relate their compounds to common uses and reactions.", "Hydrogen", "Oxygen", "Nitrogen", "Sulfur", "Halogens and their compounds"),
    "Metals and their compounds": detail("Explain metal properties, extraction, reactions, and uses.", "Reactivity series", "Metal extraction", "Iron and aluminium", "Alloys", "Corrosion prevention"),
    "Organic compounds": detail("Classify organic compounds and relate structures, reactions, and uses.", "Hydrocarbons", "Alkanols and alkanoic acids", "Esters and fats", "Amines", "Carbohydrates, proteins and polymers"),
    "Chemistry and industry": detail("Relate raw materials, processes, and products to chemical industries.", "Chemical industries", "Raw materials", "Fine and heavy chemicals", "Biotechnology", "Industrial relevance"),
    "Astronomical chemistry": detail("Describe the solar system and the chemical composition of major Earth segments.", "Solar system", "Planets", "Satellite", "Atmosphere", "Lithosphere and hydrosphere"),
  },
  Physics: {
    "Measurements and units": detail("Use physical quantities, units, instruments, and errors correctly.", "Base and derived quantities", "SI units", "Measuring instruments", "Scalars and vectors", "Errors and accuracy"),
    Motion: detail("Describe motion and use graphs and equations to solve kinematics problems.", "Distance and displacement", "Speed and velocity", "Acceleration", "Motion graphs", "Equations of motion"),
    "Gravitational field": detail("Explain gravity and apply field, force, and satellite ideas.", "Gravitational force", "Field strength", "Mass and weight", "Escape velocity", "Satellites"),
    "Equilibrium of forces": detail("Resolve forces and apply equilibrium conditions to practical systems.", "Force vectors", "Resultant force", "Moments", "Centre of gravity", "Equilibrium"),
    "Work, energy and power": detail("Apply work, energy, conservation, and power relationships.", "Work done", "Kinetic energy", "Potential energy", "Conservation of energy", "Power and efficiency"),
    Machines: detail("Explain simple machines and calculate mechanical advantage and efficiency.", "Levers", "Pulleys", "Inclined planes", "Mechanical advantage", "Velocity ratio and efficiency"),
    Elasticity: detail("Relate force, extension, and stored energy in elastic materials.", "Hooke’s law", "Stress and strain", "Elastic limit", "Springs", "Elastic potential energy"),
    Pressure: detail("Apply pressure ideas to solids, liquids, gases, and everyday devices.", "Pressure in solids", "Atmospheric pressure", "Manometers", "Barometers", "Hydraulics"),
    "Liquids at rest": detail("Explain liquid pressure, buoyancy, and flotation.", "Liquid pressure", "Pascal principle", "Upthrust", "Archimedes principle", "Floatation"),
    "Temperature and measurement": detail("Distinguish temperature from heat and use thermometric scales.", "Temperature scales", "Thermometers", "Fixed points", "Calibration", "Thermal equilibrium"),
    "Quantity of heat": detail("Calculate heat energy using specific heat capacity and latent heat ideas.", "Heat capacity", "Specific heat capacity", "Calorimetry", "Latent heat", "Heat calculations"),
    "Change of state": detail("Explain melting, boiling, evaporation, and condensation using particle ideas.", "Melting and freezing", "Boiling and evaporation", "Condensation", "Latent heat", "Pressure effects"),
    "Thermal expansion": detail("Describe expansion in solids, liquids, and gases and its applications.", "Linear expansion", "Area and volume expansion", "Bimetallic strips", "Expansion gaps", "Practical effects"),
    "Gas laws": detail("Use pressure, volume, and temperature relationships for gases.", "Boyle’s law", "Charles’ law", "Pressure law", "General gas law", "Gas calculations"),
    Vapours: detail("Explain saturated vapour, humidity, and vapour pressure.", "Evaporation", "Saturated vapour", "Vapour pressure", "Humidity", "Dew point"),
    "Structure of matter and kinetic theory": detail("Use particle motion to explain matter and gas behaviour.", "Molecular motion", "Brownian motion", "Kinetic theory", "Diffusion", "Gas pressure"),
    "Heat transfer": detail("Compare conduction, convection, and radiation and apply them in daily situations.", "Conduction", "Convection", "Radiation", "Thermal insulation", "Applications"),
    Waves: detail("Describe waves and use wave relationships to solve problems.", "Transverse and longitudinal waves", "Wavelength", "Frequency and period", "Wave speed", "Reflection and diffraction"),
    "Propagation of sound": detail("Explain how sound travels and the conditions needed for propagation.", "Sound as a wave", "Medium", "Speed of sound", "Echoes", "Resonance"),
    "Characteristics of sound": detail("Relate frequency, amplitude, and waveform to pitch and loudness.", "Pitch", "Loudness", "Quality", "Musical instruments", "Noise"),
    "Light energy": detail("Explain light sources and basic energy ideas in optical situations.", "Luminous bodies", "Light rays", "Shadows", "Illumination", "Light energy"),
    Reflection: detail("Apply laws of reflection and analyse images in mirrors.", "Plane mirrors", "Curved mirrors", "Ray diagrams", "Image properties", "Applications"),
    Refraction: detail("Explain bending of light and apply refractive-index relationships.", "Refraction", "Refractive index", "Critical angle", "Total internal reflection", "Lenses"),
    "Optical instruments": detail("Describe lenses and common optical instruments.", "Cameras", "Microscopes", "Telescopes", "Human eye", "Defects of vision"),
    "Dispersion and colours": detail("Explain colour formation, spectra, and dispersion of white light.", "Dispersion", "Spectrum", "Primary colours", "Colour mixing", "Rainbows"),
    Electrostatics: detail("Describe electric charge, fields, and electrostatic effects.", "Charge", "Charging methods", "Electric field", "Coulomb’s law", "Applications"),
    Capacitors: detail("Explain capacitance, charging, and energy storage.", "Capacitance", "Parallel plates", "Charging and discharging", "Energy storage", "Applications"),
    "Electric cells": detail("Explain cell structure, emf, internal resistance, and combinations of cells.", "Primary cells", "Secondary cells", "EMF", "Internal resistance", "Series and parallel cells"),
    "Current electricity": detail("Use current, voltage, resistance, and circuit relationships accurately.", "Current and charge", "Ohm’s law", "Resistance", "Series and parallel circuits", "Meters"),
    "Electrical energy and power": detail("Calculate electrical energy, power, and household consumption safely.", "Electrical power", "Energy consumption", "Kilowatt-hour", "Fuses", "Household safety"),
    "Magnets and magnetic fields": detail("Describe magnets, fields, and magnetic materials.", "Magnetic poles", "Field patterns", "Earth’s magnetism", "Magnetic materials", "Electromagnets"),
    "Force on a current-carrying conductor": detail("Apply motor-effect ideas to conductors and moving charges.", "Motor effect", "Fleming’s left-hand rule", "Force direction", "Electric motors", "Applications"),
    "Electromagnetic induction": detail("Explain induced emf and use generator and transformer principles.", "Magnetic flux", "Induced emf", "Lenz’s law", "Generators", "Transformers"),
    "AC circuits": detail("Describe alternating current, reactance, and simple AC circuit behaviour.", "Alternating current", "RMS values", "Reactance", "Resonance", "AC applications"),
    "Conduction of electricity": detail("Explain electrical conduction in solids, liquids, and gases.", "Metallic conduction", "Electrolytic conduction", "Gas discharge", "Conductors and insulators", "Applications"),
    "Modern physics": detail("Explain key atomic, nuclear, and quantum ideas and their applications.", "Atomic models", "X-rays", "Radioactivity", "Mass defect", "Wave–particle duality"),
    "Introductory electronics": detail("Distinguish semiconductor devices and explain basic rectification and amplification.", "Semiconductors", "P-type and N-type", "Diodes", "Transistors", "Rectification and amplification"),
    "Fibre optics and lasers": detail("Explain fibre-optic transmission and laser principles, uses, and safety.", "Optical fibres", "Total internal reflection", "Laser meaning", "Laser types", "Applications and hazards"),
  },
};

export function getSyllabusJourneyDetail(subject: SyllabusDetailSubject, topic: string): SyllabusTopicDetail | null {
  return SYLLABUS_JOURNEY_DETAILS[subject][topic] ?? null;
}
