import { Archive, ArrowRight, BookOpenCheck, Check, ChevronRight, LibraryBig, ShieldCheck, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { formatLearnerText } from "@/game/learnerText";
import { emptyArcadeProfile, readArcadeProfile, selectArcadeQuestions, type ArchiveBlueprintId, type GreatArchiveArcadeState, writeArcadeProfile } from "@/game/arcadeProfile";
import type { BankQuestion, Subject } from "@/game/types";
import "./great-archive.css";

type Phase = "setup" | "playing" | "report";
type Answer = { questionId: string; selectedIndex: number; correct: boolean };
const subjects: Subject[] = ["Use of English", "Biology", "Chemistry", "Physics"];
const blueprints: Array<{ id: ArchiveBlueprintId; title: string; note: string; target: string }> = [
  { id: "balanced", title: "Balanced Wing", note: "Place three different topic tiles to restore a broad subject wing.", target: "3 distinct topic tiles" },
  { id: "mastery", title: "Mastery Gallery", note: "Secure four true answers to deepen a single subject collection.", target: "4 secured tiles" },
  { id: "repair", title: "Repair Vault", note: "Build a careful index: secure three topic tiles and keep every miss ready for correction.", target: "3 secured tiles + repair rack" },
];

export function GreatArchive({ questions, onExit, onOpenCorrection, autoStart = false }: { questions: BankQuestion[]; onExit: () => void; onOpenCorrection: (subject: Subject, questionIds: string[]) => void; autoStart?: boolean }) {
  const [subject, setSubject] = useState<Subject>("Biology");
  const [blueprintId, setBlueprintId] = useState<ArchiveBlueprintId>("balanced");
  const [phase, setPhase] = useState<Phase>("setup");
  const [session, setSession] = useState<BankQuestion[]>([]);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [index, setIndex] = useState(0);
  const [feedback, setFeedback] = useState<"correct" | "wrong" | null>(null);
  const [archive, setArchive] = useState<GreatArchiveArcadeState>(() => emptyArcadeProfile().greatArchive);
  const [playerName, setPlayerName] = useState("");
  const saved = useRef(false); const autoStarted = useRef(false);
  const blueprint = blueprints.find((item) => item.id === blueprintId) ?? blueprints[0];
  const available = useMemo(() => questions.filter((question) => question.subject === subject), [questions, subject]);
  const current = session[index];
  const correctAnswers = answers.filter((answer) => answer.correct);
  const misses = answers.filter((answer) => !answer.correct).map((answer) => answer.questionId);
  const sessionTopics = Array.from(new Set(correctAnswers.map((answer) => session.find((question) => question.id === answer.questionId)?.topic).filter((topic): topic is string => Boolean(topic))));
  const targetMet = blueprintId === "balanced" ? sessionTopics.length >= 3 : correctAnswers.length >= (blueprintId === "mastery" ? 4 : 3);
  const wingKey = `${subject}:${blueprintId}`;

  useEffect(() => { const profile = readArcadeProfile(); setArchive(profile.greatArchive); setPlayerName(profile.displayName); }, []);
  const saveArchive = (next: GreatArchiveArcadeState) => { setArchive(next); const profile = readArcadeProfile(); writeArcadeProfile({ ...profile, greatArchive: next }); };
  const start = () => { saved.current = false; setSession(selectArcadeQuestions(available, subject, 5, archive.recentQuestionIds)); setAnswers([]); setIndex(0); setFeedback(null); setPhase("playing"); };
  useEffect(() => { if (autoStart && !autoStarted.current && phase === "setup" && available.length >= 5) { autoStarted.current = true; start(); } }, [autoStart, available.length, phase]);
  useEffect(() => {
    if (phase !== "report" || saved.current || !session.length) return;
    saved.current = true;
    const tiles = { ...archive.tiles };
    sessionTopics.forEach((topic) => { tiles[topic] = (tiles[topic] ?? 0) + 1; });
    saveArchive({ tiles, blueprints: { ...archive.blueprints, [blueprintId]: archive.blueprints[blueprintId] + (targetMet ? 1 : 0) }, restoredWings: targetMet && !archive.restoredWings.includes(wingKey) ? [...archive.restoredWings, wingKey] : archive.restoredWings, recentQuestionIds: [...archive.recentQuestionIds, ...session.map((item) => item.id)].slice(-120) });
  }, [archive, blueprintId, phase, session.length, sessionTopics, targetMet, wingKey]);
  const answer = (selectedIndex: number) => { if (!current || feedback) return; const correct = selectedIndex === current.answer_index; setAnswers((items) => [...items, { questionId: current.id, selectedIndex, correct }]); setFeedback(correct ? "correct" : "wrong"); };
  const next = () => { if (index + 1 < session.length) { setIndex((value) => value + 1); setFeedback(null); } else setPhase("report"); };

  if (phase === "setup") return <main className="great-archive" aria-labelledby="archive-title"><header className="archive-head"><button onClick={onExit}><X size={17} /> Back to arcade</button><span className="archive-brand"><i /><i /><i /><i /><b>JAMB QUEST / THE GREAT ARCHIVE</b></span><span>TOPIC-TILE STRATEGY</span></header><span className="quest-tape">QUEST TAPE / ARCHIVE RESTORATION</span><section className="archive-hero"><div><span className="eyebrow">{playerName ? `${playerName.toUpperCase()} / YOUR ARCHIVE` : "MODE 03 / ARCHITECTS OF KNOWLEDGE"}</span><h1 id="archive-title">Restore the<br /><em>knowledge halls.</em></h1><p>Every correct JAMB question places a real syllabus topic tile. Choose a blueprint, build a collection from what you actually know, and send every missing tile to the repair vault.</p><div className="archive-ledger"><span><b>{Object.values(archive.tiles).reduce((total, value) => total + value, 0)}</b> topic tiles collected</span><span><b>{archive.restoredWings.length}</b> wings restored</span></div></div><div className="archive-art"><img src="/manus-storage/great-archive-board-v2_47333bea.png" alt="Illustrated archive board with library drawers and subject symbols" /></div></section><section className="archive-setup"><div><span className="eyebrow">01 / CHOOSE A SUBJECT HALL</span><div className="archive-subjects">{subjects.map((item) => <button key={item} className={subject === item ? "active" : ""} onClick={() => setSubject(item)}><b>{item}</b><small>{questions.filter((question) => question.subject === item).length} approved question cards</small></button>)}</div></div><div><span className="eyebrow">02 / SELECT A BLUEPRINT</span><div className="archive-blueprints">{blueprints.map((item) => <button key={item.id} className={blueprintId === item.id ? "active" : ""} onClick={() => setBlueprintId(item.id)}><LibraryBig size={18} /><b>{item.title}</b><small>{item.note}</small><i>{archive.blueprints[item.id]} completed</i></button>)}</div></div></section><footer className="archive-launch"><div><span className="eyebrow">RESTORATION BRIEF</span><b>{subject} · {blueprint.title}</b><small>5 approved revision cards · goal: {blueprint.target}</small></div><button className="button button-dark" onClick={start} disabled={available.length < 5}><Archive size={17} /> Open the archive <ArrowRight size={17} /></button></footer></main>;
  if (phase === "report") return <main className="great-archive archive-report" aria-labelledby="archive-report-title"><header className="archive-head"><button onClick={onExit}><X size={17} /> Back to arcade</button><span className="archive-brand"><i /><i /><i /><i /><b>JAMB QUEST / ARCHIVE REPORT</b></span></header><section className="archive-report-hero"><span className="eyebrow">{subject.toUpperCase()} / {blueprint.title.toUpperCase()}</span><h1 id="archive-report-title">{targetMet ? "A wing is restored." : "The hall remains open."}</h1><p>{targetMet ? "Your correct answers placed the required topic tiles. The archive keeps the record factual: each label came from an approved question you solved." : "Keep the blueprint. The missing tiles are not erased; they are waiting at the repair vault for exact correction."}</p><div>{sessionTopics.length ? sessionTopics.map((topic) => <span key={topic}><Check size={14} /> {topic}</span>) : <span>No topic tiles secured yet.</span>}</div></section><section className="archive-repairs"><span className="eyebrow">REPAIR VAULT</span>{misses.length ? answers.filter((item) => !item.correct).map((item) => { const missed = session.find((question) => question.id === item.questionId); return missed ? <details key={missed.id}><summary><b>{missed.topic}</b><span>Open tile repair</span></summary><p>{formatLearnerText(missed.question)}</p><strong>Correct answer: {formatLearnerText(missed.answer_text)}</strong><small>{formatLearnerText(missed.explanation)}</small></details> : null; }) : <p className="archive-clean"><Check size={18} /> No repair cards this session. Try another blueprint or subject hall.</p>}</section><footer className="archive-report-actions"><button className="button button-dark" onClick={() => setPhase("setup")}><Archive size={16} /> Choose another blueprint</button>{misses.length ? <button className="button button-outline" onClick={() => onOpenCorrection(subject, misses)}><BookOpenCheck size={16} /> Repair {misses.length} tile{misses.length === 1 ? "" : "s"}</button> : <button className="button button-outline" onClick={onExit}>Return to arcade</button>}</footer></main>;
  return <main className="great-archive archive-play" aria-live="polite"><header className="archive-head"><button onClick={onExit}><X size={17} /> Leave archive</button><span className="archive-brand"><i /><i /><i /><i /><b>JAMB QUEST / {subject.toUpperCase()} HALL</b></span><span>CARD {index + 1} / {session.length}</span></header><section className="archive-play-ledger"><div><span>BLUEPRINT</span><b>{blueprint.title}</b></div><div><span>TILES THIS SESSION</span><b>{sessionTopics.length}</b></div><div><span>REPAIR VAULT</span><b>{misses.length} card{misses.length === 1 ? "" : "s"}</b></div></section><div className="archive-index" aria-label={`Archive index: card ${index + 1} of ${session.length}`}>{session.map((item, itemIndex) => <i key={item.id} className={itemIndex < index ? (answers[itemIndex]?.correct ? "correct" : "repair") : itemIndex === index ? "active" : ""}>{itemIndex + 1}</i>)}</div>{current && <article className="archive-question"><span className="eyebrow">ARCHIVE CARD {String(index + 1).padStart(2, "0")}</span><span className="archive-anchor"><Sparkles size={14} /> Correct answers place real JAMB syllabus topic tiles</span><h1>{formatLearnerText(current.question)}</h1><div className="archive-options">{current.options.map((option, optionIndex) => <button key={`${current.id}-${optionIndex}`} className={`${feedback && optionIndex === current.answer_index ? "correct" : ""} ${feedback === "wrong" && answers.at(-1)?.selectedIndex === optionIndex ? "wrong" : ""}`} onClick={() => answer(optionIndex)} disabled={Boolean(feedback)}><b>{String.fromCharCode(65 + optionIndex)}</b><span>{formatLearnerText(option)}</span>{feedback && optionIndex === current.answer_index && <Check size={17} />}</button>)}</div>{feedback && <div className={`archive-feedback ${feedback}`}><b>{feedback === "correct" ? `Topic tile acquired: ${current.topic}` : "This tile belongs in the repair vault."}</b><small>{feedback === "wrong" ? `Correct answer: ${formatLearnerText(current.answer_text)} — ` : ""}{formatLearnerText(current.explanation)}</small><button className="button button-dark" onClick={next}>{index + 1 === session.length ? "Read archive report" : "Place next tile"} <ChevronRight size={16} /></button></div>}</article>}</main>;
}
