import { ArrowRight, Banknote, BookOpenCheck, Building2, Check, ChevronRight, HeartPulse, Lightbulb, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { formatLearnerText } from "@/game/learnerText";
import type { BankQuestion, Subject } from "@/game/types";
import { emptyArcadeProfile, readArcadeProfile, type PresidentsDeskArcadeState, writeArcadeProfile } from "@/game/arcadeProfile";
import "./presidents-desk.css";

type MinistryId = "education" | "health" | "energy" | "innovation";
type AdviserId = "research" | "resilience" | "clarity";
type Phase = "setup" | "briefing" | "report";
type Answer = { questionId: string; selectedIndex: number; correct: boolean };
type Commonwealth = PresidentsDeskArcadeState;

const ministries: Array<{ id: MinistryId; name: string; subject: Subject; icon: typeof Building2; project: string; note: string }> = [
  { id: "education", name: "Education", subject: "Use of English", icon: Users, project: "Community Reading Network", note: "Train mentors and open reading rooms." },
  { id: "health", name: "Health", subject: "Biology", icon: HeartPulse, project: "Healthy Futures Clinic", note: "Equip a preventive-care learning clinic." },
  { id: "energy", name: "Energy", subject: "Physics", icon: Lightbulb, project: "Reliable Power Grid", note: "Connect a resilient solar-learning grid." },
  { id: "innovation", name: "Innovation", subject: "Chemistry", icon: Sparkles, project: "Materials Lab", note: "Open a safe community science laboratory." },
];
const advisers: Array<{ id: AdviserId; name: string; note: string }> = [
  { id: "research", name: "Research Office", note: "Earn +1 policy insight for each correct briefing." },
  { id: "resilience", name: "Resilience Office", note: "Protect public confidence from the first missed briefing." },
  { id: "clarity", name: "Clarity Office", note: "Show the official topic before each cabinet briefing." },
];
const blankCommonwealth = (): Commonwealth => emptyArcadeProfile().presidentsDesk;
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - .5);

export function PresidentsDesk({ questions, onExit, onOpenCorrection, autoStart = false }: { questions: BankQuestion[]; onExit: () => void; onOpenCorrection: (subject: Subject, questionIds: string[]) => void; autoStart?: boolean }) {
  const [ministryId, setMinistryId] = useState<MinistryId>("education");
  const [adviserId, setAdviserId] = useState<AdviserId>("research");
  const [phase, setPhase] = useState<Phase>("setup");
  const [briefings, setBriefings] = useState<BankQuestion[]>([]);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [feedback, setFeedback] = useState<"correct" | "wrong" | null>(null);
  const [confidenceProtected, setConfidenceProtected] = useState(false);
  const [commonwealth, setCommonwealth] = useState<Commonwealth>(blankCommonwealth);
  const autoStarted = useRef(false);
  const currentMinistry = ministries.find((item) => item.id === ministryId) ?? ministries[0];
  const adviser = advisers.find((item) => item.id === adviserId) ?? advisers[0];
  const available = useMemo(() => questions.filter((question) => question.subject === currentMinistry.subject), [questions, currentMinistry.subject]);
  const current = briefings[index];
  const correctCount = answers.filter((answer) => answer.correct).length;
  const misses = answers.filter((answer) => !answer.correct).map((answer) => answer.questionId);
  const accuracy = answers.length ? Math.round((correctCount / answers.length) * 100) : 0;
  const completedThisTerm = correctCount >= 3 && accuracy >= 60;

  useEffect(() => { setCommonwealth(readArcadeProfile().presidentsDesk); }, []);
  const saveCommonwealth = (next: Commonwealth) => { setCommonwealth(next); const profile = readArcadeProfile(); writeArcadeProfile({ ...profile, presidentsDesk: next }); };
  const start = () => { setBriefings(shuffle(available).slice(0, 5)); setIndex(0); setAnswers([]); setFeedback(null); setConfidenceProtected(false); setPhase("briefing"); };
  useEffect(() => { if (autoStart && !autoStarted.current && phase === "setup" && available.length >= 5) { autoStarted.current = true; start(); } }, [autoStart, available.length, phase]);
  const resolve = (selectedIndex: number) => { if (!current || feedback) return; const correct = selectedIndex === current.answer_index; setAnswers((items) => [...items, { questionId: current.id, selectedIndex, correct }]); if (!correct && adviserId === "resilience" && !confidenceProtected) setConfidenceProtected(true); setFeedback(correct ? "correct" : "wrong"); };
  const next = () => { if (index + 1 < briefings.length) { setIndex((value) => value + 1); setFeedback(null); return; } const projectGain = completedThisTerm ? 1 : 0; const confidenceLoss = Math.max(0, misses.length - (confidenceProtected ? 1 : 0)); saveCommonwealth({ treasury: commonwealth.treasury + correctCount * 25, confidence: Math.max(0, commonwealth.confidence - confidenceLoss + (completedThisTerm ? 1 : 0)), insight: commonwealth.insight + correctCount * (adviserId === "research" ? 2 : 1), terms: commonwealth.terms + 1, projects: { ...commonwealth.projects, [ministryId]: Math.min(3, commonwealth.projects[ministryId] + projectGain) } }); setPhase("report"); };

  if (phase === "setup") return <main className="presidents-desk" aria-labelledby="president-title"><header className="president-head"><button onClick={onExit}><X size={17} /> Back to arcade</button><span className="president-mark"><i /><i /><i /><i /><b>JAMB QUEST / ASTERRA DESK</b></span><span>FICTIONAL CIVIC STRATEGY</span></header><section className="president-hero"><div><span className="eyebrow">TERM {commonwealth.terms + 1} / CABINET BRIEFING</span><h1 id="president-title">Lead with<br /><em>what you know.</em></h1><p>Asterra is fictional. Your cabinet needs public projects, steady confidence, and honest decisions. Correct JAMB briefings fund the work; a missed briefing becomes a repair note, never a dead end.</p></div><div className="president-ledger"><span>TREASURY <b>₦{commonwealth.treasury}</b></span><span>PUBLIC CONFIDENCE <b>{commonwealth.confidence}/6</b></span><span>POLICY INSIGHT <b>{commonwealth.insight}</b></span></div></section><section className="president-setup"><div><span className="eyebrow">01 / FUND A MINISTRY</span><div className="ministry-grid">{ministries.map((item) => { const Icon = item.icon; return <button key={item.id} className={ministryId === item.id ? "active" : ""} onClick={() => setMinistryId(item.id)}><Icon size={18} /><b>{item.name}</b><small>{item.project}</small><i>{commonwealth.projects[item.id]}/3 project marks</i></button>; })}</div></div><div><span className="eyebrow">02 / CHOOSE ONE CABINET OFFICE</span><div className="adviser-grid">{advisers.map((item) => <button key={item.id} className={adviserId === item.id ? "active" : ""} onClick={() => setAdviserId(item.id)}><b>{item.name}</b><small>{item.note}</small></button>)}</div></div></section><footer className="president-launch"><div><span className="eyebrow">TODAY’S PROJECT</span><b>{currentMinistry.project}</b><small>{currentMinistry.subject} cabinet briefings · 5 decisions · {adviser.name}</small></div><button className="button button-dark" onClick={start} disabled={available.length < 5}><Building2 size={17} /> Open Cabinet <ArrowRight size={17} /></button></footer></main>;
  if (phase === "report") return <main className="presidents-desk president-report" aria-labelledby="term-report-title"><header className="president-head"><button onClick={onExit}><X size={17} /> Back to arcade</button><span className="president-mark"><i /><i /><i /><i /><b>JAMB QUEST / TERM REPORT</b></span></header><section className="president-report-hero"><span className="eyebrow">{currentMinistry.name.toUpperCase()} MINISTRY</span><h1 id="term-report-title">{completedThisTerm ? "Project advanced." : "Project needs a repair."}</h1><p>{completedThisTerm ? `${currentMinistry.project} receives its next project mark. Your cabinet turned correct briefings into a visible public result.` : "The cabinet has kept the project open. Repair the missed briefings, then return with a stronger mandate."}</p><div><span><b>{accuracy}%</b> briefing accuracy</span><span><b>{correctCount}/5</b> correct</span><span><b>{commonwealth.projects[ministryId]}/3</b> project marks</span></div></section><section className="president-repair-list"><span className="eyebrow">CABINET REPAIR NOTES</span>{misses.length ? answers.filter((item) => !item.correct).map((item) => { const missed = briefings.find((question) => question.id === item.questionId); return missed ? <details key={missed.id}><summary><b>{missed.topic}</b><span>Open briefing correction</span></summary><p>{formatLearnerText(missed.question)}</p><strong>Correct answer: {formatLearnerText(missed.answer_text)}</strong><small>{formatLearnerText(missed.explanation)}</small></details> : null; }) : <p className="president-clean"><Check size={18} /> Clean cabinet term. Choose another ministry to widen Asterra’s capacity.</p>}</section><footer className="president-report-actions"><button className="button button-dark" onClick={() => setPhase("setup")}><Building2 size={16} /> Plan another term</button>{misses.length ? <button className="button button-outline" onClick={() => onOpenCorrection(currentMinistry.subject, misses)}><BookOpenCheck size={16} /> Repair {misses.length} briefing{misses.length === 1 ? "" : "s"}</button> : <button className="button button-outline" onClick={onExit}>Return to arcade</button>}</footer></main>;
  return <main className="presidents-desk president-briefing" aria-live="polite"><header className="president-head"><button onClick={onExit}><X size={17} /> Leave cabinet</button><span className="president-mark"><i /><i /><i /><i /><b>JAMB QUEST / {currentMinistry.name.toUpperCase()}</b></span><span>{index + 1} OF {briefings.length} BRIEFINGS</span></header><section className="president-status"><div><span>PROJECT</span><b>{currentMinistry.project}</b></div><div><span>TREASURY</span><b>₦{commonwealth.treasury}</b></div><div><span>CONFIDENCE</span><b>{commonwealth.confidence - Math.max(0, answers.filter((item) => !item.correct).length - (confidenceProtected ? 1 : 0))}/6</b></div></section><div className="president-question-ledger" aria-label={`JAMB question ledger: briefing ${index + 1} of ${briefings.length}`}>{briefings.map((item, itemIndex) => <i key={item.id} className={itemIndex < index ? (answers[itemIndex]?.correct ? "correct" : "repair") : itemIndex === index ? "active" : ""}>{itemIndex + 1}</i>)}</div>{current && <article className={`president-question ${feedback ?? ""}`}><span className="eyebrow">CABINET BRIEFING {String(index + 1).padStart(2, "0")}</span><span className="president-exam-anchor"><BookOpenCheck size={14} /> JAMB revision question · approved learner bank</span>{adviserId === "clarity" && <span className="president-topic">Policy territory: {current.topic}</span>}<h1>{formatLearnerText(current.question)}</h1><div className="president-options">{current.options.map((option, optionIndex) => <button key={`${current.id}-${optionIndex}`} className={`${feedback && optionIndex === current.answer_index ? "correct" : ""} ${feedback === "wrong" && answers.at(-1)?.selectedIndex === optionIndex ? "wrong" : ""}`} onClick={() => resolve(optionIndex)} disabled={Boolean(feedback)}><b>{String.fromCharCode(65 + optionIndex)}</b><span>{formatLearnerText(option)}</span>{feedback && optionIndex === current.answer_index && <Check size={17} />}</button>)}</div>{feedback && <div className={`president-feedback ${feedback}`}><b>{feedback === "correct" ? "Briefing funded." : "This briefing needs a repair note."}</b><small>{feedback === "wrong" ? `Correct answer: ${formatLearnerText(current.answer_text)} — ` : ""}{formatLearnerText(current.explanation)}</small><button className="button button-dark" onClick={next}>{index + 1 === briefings.length ? "Read term report" : "Next briefing"} <ChevronRight size={16} /></button></div>}</article>}</main>;
}
